# Generated by Django 3.2.14 on 2022-08-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0003_alter_actor_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.FloatField(max_length=2, null=True),
        ),
    ]
