name: Mysite CI


on: [push]

jobs:
  check-unit-tests:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULEL: netflix.settings
      DEBUG: ${{ env.secrets.DEBUG }}
      SECRET_KEY: ${{ env.secrets.SECRET_KEY }}
      POSTGRES_ENGINE: ${{ env.secrets.POSTGRES_ENGINE }}
      POSTGRES_DB: ${{ env.secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ env.secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ env.secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ env.secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ env.secrets.POSTGRES_PORT }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Requirements
        run: pip3 install -r requirements.txt
      - name: Run Tests
        run: python3 manage.py test


